### ISSUE TITLE
Darwin: Get error "Killed: 9" at execution

### ISSUE THREAD

**Issue by nguyendangminh** [mattn/go-soundplayer#1]
Hi,

I'm using this package on MacOS (Darwin). It compiles successful, but at execution I get error "Killed: 9".

Currently I work round by passing "-ldflags=-s" when running `go build` or `go install`.

**Comment by mattn** [comment]
Go 1.8.1 fixes this issue.

**Comment by nguyendangminh** [comment]
Wow, I've just updated Go as your suggestion, it works. Thanks!
